[package]
name = "lenscast"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.10", package = "gtk4", features = ["gnome_47"] }
gdk = { version = "0.10", package = "gdk4" }

adw = { 
    version = "0.8",
    package = "libadwaita",
    features = ["gtk_v4_18", "v1_4"]
}

glib = "0.20"

tokio = { version = "1", features = ["rt-multi-thread", "sync"] }
async-channel = "2.5.0"

[target.'cfg(not(any(target_os = "macos", windows)))'.dependencies]
ksni = "0.3"

[profile.release]
strip = true